"""LocalUser

Revision ID: 60424aea1a23
Revises: 
Create Date: 2018-09-26 14:54:17.868337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60424aea1a23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('Userid', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('nickName', sa.VARCHAR(length=64), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('country', sa.VARCHAR(length=64), nullable=True),
    sa.Column('avatarUrl', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('Userid')
    )
    # ### end Alembic commands ###
